# Generated by Django 2.1.1 on 2018-09-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
    ]
